### ISSUE TITLE
RIP

### ISSUE THREAD

**Issue by kengsini250** [winston779/wallless#5]
唉，用了这么多年，还是没挺住啊。

**Comment by poism114514** [comment]
是跑路了吗？我看有人说wallless.xyz网址，但是发现登不上去账号

**Comment by kengsini250** [comment]
> 是跑路了吗？我看有人说wallless.xyz网址，但是发现登不上去账号

那个是骗子网站，老板应该是被抓了。

**Comment by SSETong** [comment]
哎可惜了

**Comment by yuzuki-kgr** [comment]
> 唉，用了这么多年，还是没挺住啊。

確認是寄了嗎😭

**Comment by kengsini250** [comment]
> > 唉，用了这么多年，还是没挺住啊。
> 
> 確認是寄了嗎😭

今天连节点都刷不出来了，我是不打算删了，先留着，万一呢。

**Comment by GeanQin** [comment]
不要啊，才买的一年

**Comment by yuyujulin** [comment]
MD，跑路之前先退钱啊

**Comment by kenshin20080-lab** [comment]
用了好几年了，还想着不会出啥问题，ε=(´ο｀*)))唉。。。

**Comment by kimmytse** [comment]
才冲了一年，用了一个月

**Comment by dafeiyu159** [comment]
时间大约了解清楚了，跟大家分享一下，原wallless的老板不是跑路就是进去了，然后剩下的人把软件的配色简单改了下，重新搭了个服务器继续叫wallless，软件资费跟原来一样，但是原来的账号和剩余的资费不被承认，声称前任出的问题打110解决，虽然他们公告说他们已经迁移了500个用户，但是我感觉可能就是个忽悠人的说法，而且重新开张的wallless网速只能用特别卡来形容。下载东西的速度达到了惊人的12.8KB/S左右。访问个谷歌邮箱需要等好久。

**Comment by dafeiyu159** [comment]
再多说一句，现在他们的状况很明显是需要钱来扩大服务器的服务质量的，但是花了钱的人，在现阶段登录个网页都费劲，这些人肯定要退款的，新开张的这帮人他们所谓的重新“启航”估计坚持不了多久。在这里奉劝还没入手的抓紧退。

**Comment by shiyicai** [comment]
> 时间大约了解清楚了，跟大家分享一下，原wallless的老板不是跑路就是进去了，然后剩下的人把软件的配色简单改了下，重新搭了个服务器继续叫wallless，软件资费跟原来一样，但是原来的账号和剩余的资费不被承认，声称前任出的问题打110解决，虽然他们公告说他们已经迁移了500个用户，但是我感觉可能就是个忽悠人的说法，而且重新开张的wallless网速只能用特别卡来形容。下载东西的速度达到了惊人的12.8KB/S左右。访问个谷歌邮箱需要等好久。

好奇的是换了一波人怎么还能继续，不是应该被全部没收了吗？

**Comment by dafeiyu159** [comment]
> > 时间大约了解清楚了，跟大家分享一下，原wallless的老板不是跑路就是进去了，然后剩下的人把软件的配色简单改了下，重新搭了个服务器继续叫wallless，软件资费跟原来一样，但是原来的账号和剩余的资费不被承认，声称前任出的问题打110解决，虽然他们公告说他们已经迁移了500个用户，但是我感觉可能就是个忽悠人的说法，而且重新开张的wallless网速只能用特别卡来形容。下载东西的速度达到了惊人的12.8KB/S左右。访问个谷歌邮箱需要等好久。
> 
> 好奇的是换了一波人怎么还能继续，不是应该被全部没收了吗？

不清楚现任与前任的关系，反正就是原来的wallless不能用了，新的wallless可以用，资费套餐一样，但是账号什么得重新注册。

**Comment by will584520** [comment]
真跑路了？

**Comment by alexsuzuki520** [comment]
目前新的wallless在用，确认原来的是寄了，新的需要重新注册，资费跟原来一样，有个5折券，还可以。
实际使用下来，速度是可以的，我测试了youtube视频下载，可以达到家里带宽峰值，缺点是延迟比原来普遍要高一点100ms左右，还有节点没有原来多，先充一个月用用看

**Comment by bruceliu496** [comment]
算了我用我的一元备用先顶着吧
